[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bank-rewards = "CtNhstCC9DPUMYZKvaM7uMFGxJeHQLxBwLSY3qHarTf5"
sol_trust = "FiD3EhXX6bKvWRwMEK2zuZRsaTxZoPKszVZZuxbtVpdR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = ["https://api.devnet.solana.com", "wss://api.devnet.solana.com/"]
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
